package com.wangbin.go_isp.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


@Entity
public class GoIspDbData {
    @Id(autoincrement = true)
    private Long id;
    private String rfidCode;
    private String roomName;

    @Generated(hash = 783412491)
    public GoIspDbData(Long id, String rfidCode, String roomName) {
        this.id = id;
        this.rfidCode = rfidCode;
        this.roomName = roomName;
    }

    @Generated(hash = 2101695337)
    public GoIspDbData() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRfidCode() {
        return rfidCode;
    }

    public void setRfidCode(String rfidCode) {
        this.rfidCode = rfidCode;
    }

    public String getRoomName() {
        return roomName;
    }

    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }
}
