package com.wangbin.go_isp.base.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wangbin.go_isp.bean.GoIspDbData;

import com.wangbin.go_isp.base.db.GoIspDbDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goIspDbDataDaoConfig;

    private final GoIspDbDataDao goIspDbDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goIspDbDataDaoConfig = daoConfigMap.get(GoIspDbDataDao.class).clone();
        goIspDbDataDaoConfig.initIdentityScope(type);

        goIspDbDataDao = new GoIspDbDataDao(goIspDbDataDaoConfig, this);

        registerDao(GoIspDbData.class, goIspDbDataDao);
    }
    
    public void clear() {
        goIspDbDataDaoConfig.clearIdentityScope();
    }

    public GoIspDbDataDao getGoIspDbDataDao() {
        return goIspDbDataDao;
    }

}
