package com.wangbin.go_isp.base.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wangbin.go_isp.bean.GoIspDbData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GO_ISP_DB_DATA".
*/
public class GoIspDbDataDao extends AbstractDao<GoIspDbData, Long> {

    public static final String TABLENAME = "GO_ISP_DB_DATA";

    /**
     * Properties of entity GoIspDbData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RfidCode = new Property(1, String.class, "rfidCode", false, "RFID_CODE");
        public final static Property RoomName = new Property(2, String.class, "roomName", false, "ROOM_NAME");
    }


    public GoIspDbDataDao(DaoConfig config) {
        super(config);
    }
    
    public GoIspDbDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GO_ISP_DB_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"RFID_CODE\" TEXT," + // 1: rfidCode
                "\"ROOM_NAME\" TEXT);"); // 2: roomName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GO_ISP_DB_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GoIspDbData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rfidCode = entity.getRfidCode();
        if (rfidCode != null) {
            stmt.bindString(2, rfidCode);
        }
 
        String roomName = entity.getRoomName();
        if (roomName != null) {
            stmt.bindString(3, roomName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GoIspDbData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String rfidCode = entity.getRfidCode();
        if (rfidCode != null) {
            stmt.bindString(2, rfidCode);
        }
 
        String roomName = entity.getRoomName();
        if (roomName != null) {
            stmt.bindString(3, roomName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GoIspDbData readEntity(Cursor cursor, int offset) {
        GoIspDbData entity = new GoIspDbData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // rfidCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // roomName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GoIspDbData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRfidCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRoomName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GoIspDbData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GoIspDbData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GoIspDbData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
